image: gcc:9

build:
  stage: build
  before_script:
    - apt update && apt -y install bison flex bc cpio
    - mkdir -p build
    - make O=build defconfig
    - sed -i 's/# CONFIG_STATIC is not set/CONFIG_STATIC=y/g' build/.config
  script:
    - make O=build install
  after_script:
    - mkdir -p build/_install/dev build/_install/etc/init.d build/_install/home build/_install/lib/firmware build/_install/lib/modules build/_install/mnt/p0 build/_install/mnt/p1 build/_install/mnt/p2 build/_install/proc build/_install/root build/_install/sys build/_install/tmp
    - ln -sf bin/busybox build/_install/init
    - echo "mount -v -t devtmpfs dev /dev" > build/_install/etc/init.d/rcS
    - echo "mount -v -t proc  proc /proc" >> build/_install/etc/init.d/rcS
    - echo "mount -v -t sysfs sys  /sys" >> build/_install/etc/init.d/rcS
    - echo "mount -v -t tmpfs tmp /tmp" >> build/_install/etc/init.d/rcS
    - echo "mount -v -t debugfs none /sys/kernel/debug" >> build/_install/etc/init.d/rcS
    - chmod +x build/_install/etc/init.d/rcS
    - mknod build/_install/dev/console c 5 1
    - mknod build/_install/dev/loop0 b 7 0
    - cd build/_install && find . | cpio -o --format=newc -R root:root | gzip -9 > ../initrd.img
    - cd .. && rm -rf _install
  artifacts:
    paths:
      - build/initrd.img
  cache:
    paths:
      - build

